// Builds dist/ from content/posts/*.md + static/
// Plain Node, no dependencies. Run: node build.js
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const OUT = path.join(ROOT, "dist");

function rmrf(p) { fs.rmSync(p, { recursive: true, force: true }); }
function copyDir(src, dest) {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dest, { recursive: true });
  for (const e of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, e.name), d = path.join(dest, e.name);
    if (e.isDirectory()) copyDir(s, d); else fs.copyFileSync(s, d);
  }
}

function parseFrontmatter(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!m) return { data: {}, body: raw };
  const data = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z_][\w-]*)\s*:\s*(.*)$/);
    if (!kv) continue;
    let v = kv[2].trim();
    if (/^".*"$/.test(v) || /^'.*'$/.test(v)) v = v.slice(1, -1).replace(/\\"/g, '"');
    data[kv[1]] = v;
  }
  return { data, body: raw.slice(m[0].length) };
}

// markdown subset -> the block model post.html already renders
function parseBlocks(body) {
  const lines = body.replace(/\r\n/g, "\n").split("\n");
  const blocks = [];
  let para = [];
  const flush = () => {
    if (para.length) { blocks.push({ k: "p", text: para.join(" ").trim() }); para = []; }
  };
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (/^```\s*verse\s*$/i.test(line)) {
      flush();
      const buf = [];
      i++;
      while (i < lines.length && !/^```\s*$/.test(lines[i])) { buf.push(lines[i]); i++; }
      blocks.push({ k: "verse", text: buf.join("\n").trim() });
      continue;
    }
    if (!line.trim()) { flush(); continue; }
    if (/^###\s+/.test(line)) { flush(); blocks.push({ k: "h3", text: line.replace(/^###\s+/, "").trim() }); continue; }
    if (/^##\s+/.test(line)) { flush(); blocks.push({ k: "h2", text: line.replace(/^##\s+/, "").trim() }); continue; }
    const img = line.match(/^!\[([^\]]*)\]\(([^)\s]+)\s*\)/);
    if (img) { flush(); blocks.push({ k: "img", src: img[2], text: img[1] }); continue; }
    if (/^>\s?/.test(line)) {
      flush();
      const buf = [line.replace(/^>\s?/, "")];
      while (i + 1 < lines.length && /^>\s?/.test(lines[i + 1])) { i++; buf.push(lines[i].replace(/^>\s?/, "")); }
      blocks.push({ k: "quote", text: buf.join("\n").trim() });
      continue;
    }
    para.push(line.trim());
  }
  flush();
  return blocks;
}

const MONTH_NAME = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const ACCENT = { astrology: "#e8b04b", philosophy: "#f2b240", practice: "#6ab2a0" };

rmrf(OUT);
fs.mkdirSync(OUT, { recursive: true });
copyDir(path.join(ROOT, "static"), OUT);
copyDir(path.join(ROOT, "admin"), path.join(OUT, "admin"));
fs.mkdirSync(path.join(OUT, "content"), { recursive: true });

const dir = path.join(ROOT, "content", "posts");
const files = fs.existsSync(dir) ? fs.readdirSync(dir).filter(f => /\.md$/i.test(f)) : [];
const index = [];

for (const file of files) {
  const slug = file.replace(/\.md$/i, "");
  const { data, body } = parseFrontmatter(fs.readFileSync(path.join(dir, file), "utf8"));
  if (String(data.draft) === "true") continue;
  const blocks = parseBlocks(body);
  fs.writeFileSync(path.join(OUT, "content", slug + ".json"), JSON.stringify(blocks));

  const words = blocks.reduce((n, b) => n + String(b.text || "").split(/\s+/).length, 0);
  const iso = data.published || "";
  const d = iso ? new Date(iso) : null;
  const group = (data.group || "philosophy").toLowerCase();
  index.push({
    slug,
    title: data.title || slug,
    excerpt: data.excerpt || "",
    tag: data.tag || "Writing",
    group,
    accent: data.accent || ACCENT[group] || "#e8b04b",
    read: data.read || Math.max(1, Math.round(words / 200)) + " min",
    date: data.date || (d ? MONTH_NAME[d.getUTCMonth()] + " " + d.getUTCFullYear() : ""),
    published: iso,
    cover: data.cover || "",
    href: "post.html?p=" + slug,
    _order: Number(data.order != null ? data.order : 9999)
  });
}

index.sort((a, b) =>
  (b.published || "").localeCompare(a.published || "") || a._order - b._order
);
for (const p of index) delete p._order;

fs.writeFileSync(
  path.join(OUT, "blog-index.js"),
  "// generated by build.js — do not edit\nexport const POSTS = " + JSON.stringify(index, null, 2) + ";\n"
);

const base = "https://munimarga.in";
const urls = ["/", "/readings.html", "/writing.html", "/about.html"]
  .map(u => "  <url><loc>" + base + u + "</loc></url>")
  .concat(index.map(p => "  <url><loc>" + base + "/post.html?p=" + p.slug + "</loc></url>"));
fs.writeFileSync(
  path.join(OUT, "sitemap.xml"),
  '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + urls.join("\n") + "\n</urlset>\n"
);
fs.writeFileSync(
  path.join(OUT, "robots.txt"),
  "User-agent: *\nAllow: /\nDisallow: /admin/\n\nSitemap: " + base + "/sitemap.xml\n"
);

console.log("built " + index.length + " posts -> dist/");
